name: 'Set up GitHub Actions caching for Turborepo'
description: 'Sets up Turborepo Remote Caching using GitHub Actions’ built-in cache instead of Vercel'
author: 'Thai Pangsakulyanont'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'post.js'
